server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: https://library-auth-service.onrender.com
          predicates:
            - Path=/api/auth/**,/api/users/**

        - id: catalog-service
          uri: https://library-catalog-service.onrender.com
          predicates:
            - Path=/api/books/**,/api/categories/**

        - id: circulation-service
          uri: https://library-circulation-service.onrender.com
          predicates:
            - Path=/api/borrows/**,/api/reservations/**

        - id: engagement-service
          uri: https://library-engagement-service.onrender.com
          predicates:
            - Path=/api/favorites/**,/api/reviews/**

        - id: report-service
          uri: https://library-report-service.onrender.com
          predicates:
            - Path=/api/reports/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway